- hosts: all
  become: true

  tasks:
    - name:
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name:
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name:
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
        state: present

    - name: 
      apt:
        update_cache: yes

    - name:
      apt:
        name: docker-ce
        state: present

    - name:
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name:
      command: docker-compose --version

    - name:
      copy:
        dest: /home/ubuntu/docker-compose.yml
        content: |
          version: '3'
          services:
            nginx:
              image: nginx:latest
              ports:
                - "80:80"

    - name:
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu
